---
hub: "cdcepi/FluSight-forecast-hub/"
title: "FluSight Forecast Hub Dashboard"
html:
  include-in-header:
    - text: |
        <!-- Default Statcounter code for CDC FluSight Hub Dashboard https://reichlab.io/flusight-dashboard/ -->
        <script type="text/javascript">
        var sc_project=13093554;
        var sc_invisible=1;
        var sc_security="e010bf14";
        </script>
        <script type="text/javascript"
        src="https://www.statcounter.com/counter/counter.js"
        async></script>
        <noscript><div class="statcounter"><a title="Web Analytics"
        href="https://statcounter.com/" target="_blank"><img
        class="statcounter"
        src="https://c.statcounter.com/13093554/0/e010bf14/1/"
        alt="Web Analytics"
        referrerPolicy="no-referrer-when-downgrade"></a></div></noscript>
        <!-- End of Statcounter Code -->
        </script>
